name: babysitting

on:
  workflow_call:
    inputs:
      input_param:
        type: string

jobs: 
  # checkout: 
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get code
  #       uses: actions/checkout@v3

  SAST:
    uses: ./.github/workflows/sast.yaml
  
  Build:
    uses: ./.github/workflows/build.yaml
    needs: SAST

  Package:
    uses: ./.github/workflows/package.yaml
    needs: Build
  
  Deploy:
    uses: ./.github/workflows/deploy.yaml
    needs: Package