name: babysitting

on:
  workflow_call:
    inputs:
      input_param:
        type: string

env:
  MY_VAR: ${{ github.env.MY_VAR }}

jobs: 
  # checkout: 
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get code
  #       uses: actions/checkout@v3

  SAST:
    uses: ./.github/workflows/sast.yaml
    with:
      input_param: ${{ inputs.input_param }}
  
  Build:
    uses: ./.github/workflows/build.yaml
    needs: SAST
    with:
      MY_VAR: ${{ github.env.MY_VAR }}

  Package:
    uses: ./.github/workflows/package.yaml
    needs: Build
  
  Deploy:
    uses: ./.github/workflows/deploy.yaml
    needs: Package