name: babysitting

on:
  workflow_call:

jobs: 
  # checkout: 
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get code
  #       uses: actions/checkout@v3

  Build:
    uses: ./.github/workflows/build.yaml

  SAST:
    uses: level4cloud-org/devops_library/.github/workflows/sast.yaml@babysitting


      # - name: Package
      #   uses: level4cloud-org/devops_library/.github/workflows/package.yaml

      # - name: Deploy
      #   uses: level4cloud-org/devops_library/.github/workflows/deploy.yaml
