name: babysitting

on:
  workflow_call:

jobs: 
  babysitting: 
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      # - name: Build
      #   uses: level4cloud-org/devops_library/.github/workflows/build.yaml

      - name: SAST
        uses: level4cloud-org/devops_library/.github/workflows/sast.yaml

      - name: Package
        uses: level4cloud-org/devops_library/.github/workflows/package.yaml

      - name: Deploy
        uses: level4cloud-org/devops_library/.github/workflows/deploy.yaml
