name: babysitting

on:
  workflow_call:
    inputs:
      input_param:
        required: true
        type: string

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Input Param
        run: echo "Input param is ${{ inputs.input_param }}"

  package: 
    runs-on: ubuntu-latest
    steps:
      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          username: mlops_username
          password: ${{ secrets.HARBOR_TOKEN }}
