name: babysitting

on:
  workflow_call:

jobs: 
  babysitting: 
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      # - name: Build
      #   uses: ./.github/workflows/build.yaml

      - name: SAST
        uses: .github/workflows/sast.yaml@babysitting
        with:
          repository: level4cloud-org/devops_library
          event-type: run-pipeline
          client-payload: '{"ref": "babysitting"}'


      # - name: Package
      #   uses: level4cloud-org/devops_library/.github/workflows/package.yaml

      # - name: Deploy
      #   uses: level4cloud-org/devops_library/.github/workflows/deploy.yaml
