on:
  workflow_call:

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Instalar dependências
        run: |
          python -m venv .venv
          pip install -r requirements.txt
      
      - name: Logar no Docker Hub ou Harbor (Padrão Claro)
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push da imagem para Docker Hub ou Harbor (Padrão Claro)
        run: docker push myapp:latest