name: babysitting

on:
  workflow_call:
    inputs:
      PROJECT_NAME:
        type: string
      INPUT_PARAM:
        type: string

jobs:

  SAST:
    uses: ./.github/workflows/sast.yaml
    with:
      INPUT_PARAM: ${{ inputs.INPUT_PARAM }}

  Build:
    uses: ./.github/workflows/build.yaml
    needs: SAST
    with:
      PROJECT_NAME: ${{ inputs.PROJECT_NAME }}

  Tagging_git:
    uses: ./.github/workflows/tag-git.yaml
    with:
      PROJECT_NAME: ${{ inputs.PROJECT_NAME }}

  Package:
    uses: ./.github/workflows/package.yaml
    needs: Build

  # Tagging_Model:
  #   uses: ./.github/workflows/tag-model.yaml
  #   needs: Package

  Pipelines_OCI:
    uses: ./.github/workflows/package.yaml
    needs: Build

  Deploy:
    uses: ./.github/workflows/deploy.yaml
    needs: Package