on:
  workflow_call:  

jobs:  
  package: 
        runs-on: ubuntu-latest
        steps:
          - name: Echo Var Package
            run: echo "A variável local é ${{ github.env.MY_VAR }}" 

        # - name: Login to Harbor
        #   uses: docker/login-action@v3
        #   with:
        #     username: mlops_username
        #     password: ${{ secrets.HARBOR_TOKEN }}