name: babysitting

on:
  workflow_call:  

jobs:  
  package: 
        runs-on: ubuntu-latest
        steps:
        - name: Login to Harbor
          uses: docker/login-action@v3
          with:
            username: mlops_username
            password: ${{ secrets.HARBOR_TOKEN }}