on:
  workflow_call:
    inputs:
      input_param:
        type: string

jobs: 
  SAST: 
    runs-on: ubuntu-latest
    steps:
      - name: Echo Var SAST
        run: echo "A variável local é $input_param"